name: progressive_cached_network_image_cdn
description: Load images from network and cache them with cached_network_image
  and resize it with ImageCDN
version: 1.0.0+1
homepage: https://github.com/nizwar/image_network_resizer.git

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
     